#!/bin/bash

BASE="$HOME/Documents/Organized Documents CLEAN"

echo "Creating Organized Documents CLEAN..."
echo "Location: $BASE"
echo ""

dirs=(
  "@Command Center"
  "2BOrganized"
  "Babysitter Shared"
  "Pet Sitter Shared"
  "Miscellaneous"
  "Personal"
  "Software Licences/Codes"
  "Software Licences/Documents"
  "Business/Client Files/Client Contact Info"
  "Business/Client Files/Client Feedback"
  "Business/Client Files/Project Briefs"
  "Business/Client Files/Proposals and Quotes"
  "Business/Contracts & Agreements/Client Contracts"
  "Business/Contracts & Agreements/Non-Disclosure Agreements"
  "Business/Contracts & Agreements/Partnership Agreements"
  "Business/Contracts & Agreements/Vendor Agreements"
  "Business/Employee Info/Employee Contracts"
  "Business/Employee Info/Payroll Information"
  "Business/Employee Info/Performance Reviews"
  "Business/Employee Info/Training and Development Records"
  "Business/Employment Documents/Checks"
  "Business/Employment Documents/Contracts"
  "Business/Employment Documents/Cover Letters"
  "Business/Employment Documents/Pay Stubs"
  "Business/Employment Documents/Performance Reviews"
  "Business/Employment Documents/Professional Development"
  "Business/Employment Documents/Resumes"
  "Business/Financial Documents/Bank Statements"
  "Business/Financial Documents/Enterprise Risk Assessment"
  "Business/Financial Documents/Expense Reports"
  "Business/Financial Documents/Invoices"
  "Business/Financial Documents/Receipts"
  "Business/Financial Documents/Tax Documents"
  "Business/Legal/Business Licenses and Permits"
  "Business/Legal/Compliance Documents"
  "Business/Legal/Legal Correspondence"
  "Business/Legal/Trademark and Patent"
  "Business/Marketing/Advertising Materials"
  "Business/Marketing/Branding Guidelines"
  "Business/Marketing/Marketing Plans and Strategies"
  "Business/Marketing/Social Media Content"
  "Business/Marketing/Website Materials"
  "Business/Miscellaneous"
  "Business/Pitches"
  "Business/Product:Service Info/Inventory Records"
  "Business/Product:Service Info/Pricing Information"
  "Business/Product:Service Info/Product Manuals"
  "Business/Product:Service Info/Service Descriptions"
  "Business/Professional Development/Certificates"
  "Business/Professional Development/Courses"
  "Business/Professional Development/Workshops"
  "Business/Project Management/Correspondence with Team members"
  "Business/Project Management/Meeting Notes"
  "Business/Project Management/Project Plans"
  "Business/Project Management/Timelines and Schedules"
  "Business/Proposals/Proposal Research"
  "Business/Sales/Leads and Customer Info"
  "Business/Sales/Pricing and Product Info"
  "Business/Sales/Sales Presentations"
  "Business/Sales/Sales Reports"
  "Business/Software Licenses"
  "Business/Tech"
  "Education/Anna/Admission Documents/Admission Letters"
  "Education/Anna/Admission Documents/Enrollment Forms"
  "Education/Anna/Admission Documents/Financial Aid Docs"
  "Education/Anna/Admission Documents/Scholarship Awards and Info"
  "Education/Anna/Course Materials/Assignments"
  "Education/Anna/Course Materials/Lecture Notes"
  "Education/Anna/Course Materials/Reading Materials & Textbooks"
  "Education/Anna/Course Materials/Research Papers and Projects"
  "Education/Anna/Course Materials/Syllabi"
  "Education/Anna/Diplomas and Certificates"
  "Education/Anna/Extracurricular Activities/Awards"
  "Education/Anna/Extracurricular Activities/Club Memberships"
  "Education/Anna/Extracurricular Activities/Sports Participation Records"
  "Education/Anna/Extracurricular Activities/Volunteer Experience"
  "Education/Anna/Financial Documents/Education Related Expenses"
  "Education/Anna/Financial Documents/Scholarship Details"
  "Education/Anna/Financial Documents/Student Loan Info"
  "Education/Anna/Financial Documents/Tuition Fee Receipts"
  "Education/Anna/Miscellaneous"
  "Education/Anna/Professional Development/Letters of Recommendation"
  "Education/Anna/Professional Development/Networking Contacts"
  "Education/Anna/Professional Development/Resume & Cover Letters"
  "Education/Anna/Professional Development/Workshop and Seminar Info"
  "Education/Anna/Relevant Screenshots"
  "Education/Anna/Research/Conference Presentations"
  "Education/Anna/Research/Published Papers"
  "Education/Anna/Research/Research Grants and Funding Information"
  "Education/Anna/Research/Research Proposals"
  "Education/Anna/Research/Thesis"
  "Education/Anna/Study Abroad/Foreign University Admission and Enrollment Documents"
  "Education/Anna/Study Abroad/International Insurance Information"
  "Education/Anna/Study Abroad/Passport:Visa Copies"
  "Education/Anna/Study Abroad/Travel Itineraries"
  "Education/Anna/Transcripts and Grades/College:University Transcripts"
  "Education/Anna/Transcripts and Grades/High School Transcripts"
  "Education/Anna/Transcripts and Grades/Report Cards"
  "Education/Anna/Transcripts and Grades/Standardized Test Scores"
  "Education/Sakura/Admission Documents/Admission Letters"
  "Education/Sakura/Admission Documents/Enrollment Forms"
  "Education/Sakura/Admission Documents/Financial Aid Docs"
  "Education/Sakura/Admission Documents/Scholarship Awards and Info"
  "Education/Sakura/Course Materials/Assignments"
  "Education/Sakura/Course Materials/Lecture Notes"
  "Education/Sakura/Course Materials/Reading Materials & Textbooks"
  "Education/Sakura/Course Materials/Research Papers and Projects"
  "Education/Sakura/Course Materials/Syllabi"
  "Education/Sakura/Diplomas and Certificates"
  "Education/Sakura/Extracurricular Activities/Awards"
  "Education/Sakura/Extracurricular Activities/Club Memberships"
  "Education/Sakura/Extracurricular Activities/Sports Participation Records"
  "Education/Sakura/Extracurricular Activities/Volunteer Experience"
  "Education/Sakura/Financial Documents/Education Related Expenses"
  "Education/Sakura/Financial Documents/Scholarship Details"
  "Education/Sakura/Financial Documents/Student Loan Info"
  "Education/Sakura/Financial Documents/Tuition Fee Receipts"
  "Education/Sakura/Miscellaneous"
  "Education/Sakura/Transcripts and Grades"
  "Education/Sakura/Weiss High School"
  "Family Shared/Adoption Papers"
  "Family Shared/Advocacy"
  "Family Shared/Anna Hardship/Non-Profit Research"
  "Family Shared/Anna Hardship/Reports and Summaries"
  "Family Shared/Anna Hardship/Requests for Assistance"
  "Family Shared/Benefits Applications/Anna"
  "Family Shared/Benefits Applications/Olga"
  "Family Shared/Benefits Applications/Sakura"
  "Family Shared/Birth Certificate Backup"
  "Family Shared/CPS"
  "Family Shared/Family Feuds"
  "Family Shared/Family Recipes"
  "Family Shared/Identification/Birth Certificate"
  "Family Shared/Identification/Drivers License"
  "Family Shared/Identification/Passport"
  "Family Shared/Mail and Relocation Documents"
  "Family Shared/Marriage Certificate Backup"
  "Family Shared/Medical Records/Family Medical Information"
  "Family Shared/Medical Records/Immunization Records"
  "Family Shared/Medical Records/Insurance Information"
  "Family Shared/Medical Records/Pets Medical Information"
  "Family Shared/Name Change Documents"
  "Family Shared/Passport Backup"
  "Family Shared/Password Backup"
  "Family Shared/Photos/Anna"
  "Family Shared/Photos/Sakura"
  "Family Shared/Power Of Attorney Backup"
  "Family Shared/SSN"
  "Family Shared/Sakura Estate/Claims"
  "Family Shared/Sakura Estate/ERS"
  "Family Shared/Sakura Estate/Final Accounting"
  "Family Shared/Sakura Estate/Financial Plans"
  "Family Shared/Sakura Estate/Formal Updates and Summaries"
  "Family Shared/Sakura Estate/Frost Statements"
  "Family Shared/Sakura Estate/HOA"
  "Family Shared/Sakura Estate/House Appraisal Protests"
  "Family Shared/Sakura Estate/House Damages"
  "Family Shared/Sakura Estate/Inheritance Taxes"
  "Family Shared/Sakura Estate/Mail"
  "Family Shared/Sakura Estate/Nigel Documents"
  "Family Shared/Sakura Estate/Property Taxes"
  "Family Shared/Sakura Estate/Sakura Hardship"
  "Family Shared/Sakura Estate/Warranty Fraud"
  "Finance/Banking/Anna"
  "Finance/Banking/Sakura"
  "Finance/Bills and Utilities/ATT"
  "Finance/Bills and Utilities/Atmos"
  "Finance/Bills and Utilities/Green Mountain Energy"
  "Finance/Bills and Utilities/Monthly Utility Bills"
  "Finance/Bills and Utilities/Other Recurring Bills"
  "Finance/Bills and Utilities/Rent:Mortgage Receipts"
  "Finance/Bills and Utilities/Spectrum"
  "Finance/Credit Cards/Credit Card Contact Info"
  "Finance/Credit Cards/Credit Card Statements"
  "Finance/Credit Cards/Credit Score Reports"
  "Finance/Insurance/Auto Insurance Policies"
  "Finance/Insurance/Health Insurance Information"
  "Finance/Insurance/Home Insurance Documents"
  "Finance/Insurance/Life Insurance Policies"
  "Finance/Insurance/Property Insurance"
  "Finance/Investments/Buy:Sell Transaction Records"
  "Finance/Investments/Investment Account Information"
  "Finance/Investments/Mutual Fund Statements"
  "Finance/Investments/Portfolio Statements"
  "Finance/Loans/Car Loan Documents"
  "Finance/Loans/Mortgage Documents"
  "Finance/Loans/Personal Loan Documents"
  "Finance/Loans/Student Loan Information"
  "Finance/Real Estate/Home Purchase Documents"
  "Finance/Real Estate/Lease Agreements"
  "Finance/Real Estate/Property Deeds"
  "Finance/Real Estate/Real Estate Investment Records"
  "Finance/Retirement/401k Info"
  "Finance/Retirement/IRA Information"
  "Finance/Retirement/Pension Documents"
  "Finance/Retirement/Social Security Information"
  "Finance/Tax Documents/Federal & State Tax Returns"
  "Finance/Tax Documents/Property Tax Records"
  "Finance/Tax Documents/Receipts for Tax-Deductible Expenses"
  "Finance/Tax Documents/W2 & 1099 Forms"
  "Hobby/AI Art"
  "Hobby/Biology"
  "Hobby/Civil Rights Research/Relevant Screenshots"
  "Hobby/Collecting/History"
  "Hobby/Collecting/Inventory of Collection"
  "Hobby/Collecting/Purchase or Appraisal Receipts"
  "Hobby/Comedy"
  "Hobby/Cooking/Cooking or Baking Tutorials"
  "Hobby/Cooking/Meal Plans"
  "Hobby/Cooking/Photos of Dishes"
  "Hobby/Cooking/Recipes"
  "Hobby/Creative Writing"
  "Hobby/Gardening/Garden Layouts and Plans"
  "Hobby/Gardening/Photos of Garden"
  "Hobby/Gardening/Plant Care Guides"
  "Hobby/Geopolitics"
  "Hobby/Music/Equipment Manuals"
  "Hobby/Music/Recording Files"
  "Hobby/Music/Research Papers"
  "Hobby/Music/Screenshots"
  "Hobby/Music/Sheet Music or Tabs"
  "Hobby/My Movies/Documents"
  "Hobby/My Movies/Movies"
  "Hobby/Paintings"
  "Hobby/Photography"
  "Hobby/Psychology"
  "Hobby/Reading"
  "Hobby/Sports/Competition Information"
  "Hobby/Sports/Equipment Manuals and Purchase Information"
  "Hobby/Sports/Progress Trackers or Logs"
  "Hobby/Sports/Workout Plans and Routines"
  "Hobby/Tech/Active_Inference"
  "Hobby/Tech/Automation"
  "Hobby/Tech/NLP"
  "Hobby/Tech/Python_GUI"
  "Hobby/Travel/Packing Lists"
  "Hobby/Travel/Travel Guides"
  "Hobby/Travel/Travel Itineraries"
  "Home/Home Maintenance/Appliance Manuals"
  "Home/Home Maintenance/Renovations"
  "Home/Home Maintenance/Repairs"
  "Home/Insurance/Auto Insurance"
  "Home/Insurance/Claims"
  "Home/Insurance/Home Insurance"
  "Home/Utilities/Cable:Internet"
  "Home/Utilities/Electricity"
  "Home/Utilities/Phone"
  "Home/Utilities/Water"
  "LEGAL_AND_ADVOCACY/00_TEMPLATES/Standard_Litigation_Folder_Hierarchy"
  "LEGAL_AND_ADVOCACY/01_TRAVIS_COUNTY_AND_LOCAL/01_PROBATE_COURT"
  "LEGAL_AND_ADVOCACY/01_TRAVIS_COUNTY_AND_LOCAL/01.2_STATE_DISTRICT_COURT"
  "LEGAL_AND_ADVOCACY/01_TRAVIS_COUNTY_AND_LOCAL/02_JUSTICE_PEACE_2"
  "LEGAL_AND_ADVOCACY/01_TRAVIS_COUNTY_AND_LOCAL/02.1_JUSTICE_PEACE_1"
  "LEGAL_AND_ADVOCACY/01_TRAVIS_COUNTY_AND_LOCAL/02.2_JUSTICE_PEACE_5"
  "LEGAL_AND_ADVOCACY/01_TRAVIS_COUNTY_AND_LOCAL/03_MUNICIPAL_CRIMINAL"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.1_Administrative_PUC_SOAH"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.2_Professional_Grievances"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.3_TWC_Civil_Rights_and_Labor"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.4_HHSC_AND_BENEFITS"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.5_DMV"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.6_Antisemitic_Commission"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.7_Social_Media"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.8_Third_Court_Appeals"
  "LEGAL_AND_ADVOCACY/02_TEXAS_STATE_AND_OVERSIGHT/02.9_Supreme_Court"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.1_Immigration_Identity"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.2_Civil_Rights_Title_VI"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.3_Strategic_Dashboards"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.4_US_DISTRICT_COURT"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.5_US_CIRCUIT_COURT"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.6_FBI"
  "LEGAL_AND_ADVOCACY/03_FEDERAL_AND_SOVEREIGN/03.7_EEOC"
  "LEGAL_AND_ADVOCACY/05_FEDERAL_SUBMISSION"
  "LEGAL_AND_ADVOCACY/06_Website"
)

for dir in "${dirs[@]}"; do
  mkdir -p "$BASE/$dir"
  touch "$BASE/$dir/.gitkeep"
done

echo ""
echo "✓ Done! Organized Documents CLEAN folder created."
echo "✓ Location: $BASE"
echo ""
